stages:
  - build
  - deploy


build:gitlab:
  stage: build  
  tags:
    - npm
    - windows
  artifacts:
    paths:
    - .dist/gitlab
  script:
    - Copy-Item -Path F:\jk\atk-doc\node_modules -Destination $PWD -Recurse
    - npm run build:gitlab

build:standalone:
  stage: build  
  tags:
    - npm
    - windows
  artifacts:
    paths:
    - .dist/standalone
  script:
    - Copy-Item -Path F:\jk\atk-doc\node_modules -Destination $PWD -Recurse
    - npm run build:standalone

build:standalone-kylin:
  stage: build  
  tags:
    - npm
    - windows
  artifacts:
    paths:
    - .dist/standalone-kylin
  script:
    - Copy-Item -Path F:\jk\atk-doc\node_modules -Destination $PWD -Recurse
    - npm run build:standalone-kylin


.deploy:pages-old:
  stage: deploy
  tags:
    - linux
    - gitlab
  dependencies:
    - build:gitlab
    - build:standalone
  script:
    - cp -r .dist/gitlab/* /mnt/project/gitlab/gitlab-rails/shared/pages/jinke18/atk-doc
    - zip -r /mnt/project/gitlab/gitlab-rails/shared/pages/jinke18/atk-doc/help-standalone.zip .dist/standalone/


deploy:pages:
  stage: deploy
  tags:
    - linux
    - gitlab
  dependencies:
    - build:gitlab
    - build:standalone
    - build:standalone-kylin
  script:
    #- mkdir ./public || true
    - cp  -r .dist/gitlab/* /var/opt/gitlab/gitlab-rails/shared/pages
    - zip -r /var/opt/gitlab/gitlab-rails/shared/pages/help-standalone.zip        .dist/standalone/
    - zip -r /var/opt/gitlab/gitlab-rails/shared/pages/help-standalone-kylin.zip  .dist/standalone-kylin/
  